# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Setup
    init: npm i -g @frctl/fractal npm@latest # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
vscode:
  extensions:
    - ahmadawais.emoji-log-vscode
    - albert.tabout
    - aliariff.auto-add-brackets
    - chrmarti.regex
    - csstools.postcss
    - donjayamanne.githistory
    - editorconfig.editorconfig
    - esbenp.prettier-vscode
    - formulahendry.auto-close-tag
    - formulahendry.auto-rename-tag
    - gruntfuggly.todo-tree
    - jrebocho.vscode-random
    - meganrogge.template-string-converter
    - mrmlnc.vscode-duplicate
    - ms-vscode.live-server
    - okitavera.vscode-nunjucks-formatter
    - pnp.polacode
    - qcz.text-power-tools
    - ronnidc.nunjucks
    - shardulm94.trailing-spaces
github:
  prebuilds:
    addBadge: true
    addComment: true
    branches: false
    master: false
image:
  file: .gitpod.Dockerfile
